# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ronald Smith
title: Tier 3 Helpdesk
email: mr.ron.c.smith@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  Magnathia
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: mr ron c smith
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
## additional_links:
## - title: itsgoingto.be
##   icon: fas fa-globe
##   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Ron and I currently hold the position of Tier 3 helpdesk Lead at the Pacific Marine Environmental Labratory (PMEL).
  I am also skilled in <mark>Python scripting</mark>, <mark>Powershell</mark>, <mark>Java</mark>, <mark>C#</mark>. I run my own home lab that includes <mark>Microsoft Active Directory</mark>, <mark>Kubernetes</mark>, <mark>Docker</mark>, <mark>Wuzah Security monitoring</mark>, <mark>Ansible AWX</mark>, and any other projects that I get interested in.
  Besides preforming Helpdesk opperations and leading a team to do so, I have experiance in <mark>Devops</mark>, <mark>Software and Web Application development</mark>, <mark>Deep learning Neural Networks</mark>, <mark>Data Science</mark>, <mark>System and Network Administration</mark> (Windows, Mac and Linux), and dabble in <mark>PEN testing</mark> / <mark>Red team opperations</mark>.
  I am an Army combat veteran and belive that security should be part of every development and deployment cycle.

  I am most skilled in: <mark>Python</mark> and <mark>Ark Survival Ascended</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Project Euler
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Solving interesting problems in creative ways
        description: | # this will include new lines to allow paragraphs
          I started this project as a way to document my <mark>Python</mark> and <mark>Problem Solving</mark> skills. Challenges are located at projecteuler.net and present problems that can be both brute forced or solved efficiently when scailed up. Great examples keeping effecency in mind when solving problems.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Datavise Inc.
        link: datavise.net
        # link_text: datavise.net
        sub_title: Tier 3 Helpdesk
        caption: October 2020 - Present
        quote: >
          Supporting the science of NOAA and the security of the US Government.
        description: | # this will include new lines to allow paragraphs
            Balancing security and innovation is a tough job.
            During my time supporting the science of PMEL, I have learned that making a secure system also needs to be user friendly.
            I lead a team of 4 others that are responsible for provisioning, and maintaining almost 200 end user work stations as well as instrumentation systems.
            Some responsibilities include:
            * Security patching
            * Microsoft Active Directory management
            * DNS management using Infoblox
            * Infrastructure tracking using in house developed web application PNDI
            * Frontline help desk support
            * Workstation Administration
            * Device provisioning and imaging (Mac and Windows)
            * Mac configuration management using JAMF
            * PC configuration management using SCCM
            * Process and change management documentation generation and maintainance
             
      - layout: left
        title: Hostwinds.
        link: hostwinds.com
        # link_text: Hostwinds.com
        sub_title: Frontline Support Manager.
        caption: November 2017 - October 2020
        quote: >
          Sales, Support and Development for a growing webhosting company.

        description: | # this will include new lines to allow paragraphs
            From server installation in a datacenter to full support for whatever your webhosting needs.
            Being the first and often single point of contact for hundreds of end users, resolving there issues is a tough job.
            Add on top of it doing sales and support tickets, phone sales and support, and live chat sales and support, and you can start to see how the job is not for everyone.
            I lead a team over various shifts of 30 people to accomplish this mission. I was one of 3 people writing single click install scripts for <mark>OpenStack</mark>.
            I also preformed <mark>datacenter opperations</mark> from something as simple as swaping out a failing drive in a raid array to fully configuring a new server rack with all the switches, load balancing power, imaging and setting up security on servers and importing them into our CWHM for use as VPS and shared hosting solutions for our customers.
            Later as part of fully custom Web Host management system development process, I integrated Ansible into stack so we could facilitate installing multiple services to a single systems.
            Another project I worked on, I developed a complete monitoring solution for both internal and customer use. This made sure services were 100% opperational and automatically recovered incase of failure.
            This project also monitored our entire IP space, checking all the IP addresses (~400,000 ip addresses) for email black list, Regional blocking, and abuse reports.
            At first, this project was just multiprocessed and multithreaded, running asyncronously in Python. Later I turned this into a docker container and expanded it dynamically using Kubernetes, so I could provide 5 minute interval testing across our entire IP space.
            Skills I used on a daily basis include but not limited to:
            * 7 layer network model
            * soft skills / customer communication
            * Linux support
            * Windows Support
            * cPanel support
            * WHM support
            * Python, bash, and Javascript
            * Docker
            * Kubernetes
            * Django and Flask
            * PHP

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Southern New Hampshire University
        caption: 2017 - 2019
        sub_title: BS Game Development and Design
        quote: >
          Something something something...
        description: | # this will include new lines to allow paragraphs
          Still coping with being a civilian and working full time, I needed a change in my life. I first picked up Python programing by learning Pygame.
          These skills taught me the basic structure of programing that I later used for automation and data science.
          I chose to do Game development and design to follow the same mentality that brought me to coding in the first place and learned a ton about other programing languages like Java and C#.
          I attended school online alongside my wife and in the first year we made the deans list!

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In my personal life I am largly a family man. I enjoy love learning new things and keeping my skills sharp. Some other interests and hobbies are:
      - Gaming
      - Fishing
      - Wood working
      - Automating my home and daily tasks

      Checkout my Linkedin for certification and more details!

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
